/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sudoku_jlib {
  public static SWIGTYPE_p_unsigned_char new_uint8Array(int nelements) {
    long cPtr = sudoku_jlibJNI.new_uint8Array(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static void delete_uint8Array(SWIGTYPE_p_unsigned_char ary) {
    sudoku_jlibJNI.delete_uint8Array(SWIGTYPE_p_unsigned_char.getCPtr(ary));
  }

  public static short uint8Array_getitem(SWIGTYPE_p_unsigned_char ary, int index) {
    return sudoku_jlibJNI.uint8Array_getitem(SWIGTYPE_p_unsigned_char.getCPtr(ary), index);
  }

  public static void uint8Array_setitem(SWIGTYPE_p_unsigned_char ary, int index, short value) {
    sudoku_jlibJNI.uint8Array_setitem(SWIGTYPE_p_unsigned_char.getCPtr(ary), index, value);
  }

  public static int getL_CONST_RESULT_BUFFER_SIZE() {
    return sudoku_jlibJNI.L_CONST_RESULT_BUFFER_SIZE_get();
  }

  public static int get_sudoku_solution_STUB(String in_request, SWIGTYPE_p_unsigned_char out_response, int[] out_runtime) {
    return sudoku_jlibJNI.get_sudoku_solution_STUB(in_request, SWIGTYPE_p_unsigned_char.getCPtr(out_response), out_runtime);
  }

  public static int get_sudoku_possible_moves_STUB(String in_request, SWIGTYPE_p_unsigned_char out_response, int[] out_runtime) {
    return sudoku_jlibJNI.get_sudoku_possible_moves_STUB(in_request, SWIGTYPE_p_unsigned_char.getCPtr(out_response), out_runtime);
  }

}
