/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sudoku_jlibJNI {
  public final static native long new_uint8Array(int jarg1);
  public final static native void delete_uint8Array(long jarg1);
  public final static native short uint8Array_getitem(long jarg1, int jarg2);
  public final static native void uint8Array_setitem(long jarg1, int jarg2, short jarg3);
  public final static native int L_CONST_RESULT_BUFFER_SIZE_get();
  public final static native int get_sudoku_solution_STUB(String jarg1, long jarg2, int[] jarg3);
  public final static native int get_sudoku_possible_moves_STUB(String jarg1, long jarg2, int[] jarg3);
}
